In [55]:
import pandas as pd
import numpy as np


In [56]:
# The code was removed by Watson Studio for sharing.

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0    649                             0.001        27384   51150   
1  81136                             0.124        23735  285140   
2  70762                             1.000        17170  186030   
3  53935                             0.198        16068  123540   
4  15476                             0.041        10591  200020   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    0.0                     0.0   
3                    0.0                     0.0   
4                    1.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.89   
1                             0.0                           98.93   
2                             0.0                             NaN   
3                             0.0                           99.00   
4                             0.0                           99.17   

   no_of_premiums_paid sourcing_channel residence_area_type  
0                    7                A               Rural  
1                   19                A               Urban  
2                    2                B               Urban  
3                   11                B               Rural  
4                   14                A               Rural

In [57]:

body = client_72078df4714c4f6faaf918e0f5908679.get_object(Bucket='datascience-donotdelete-pr-aqjf1vvulndmss',Key='train_qnU1GcL (1).csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train = pd.read_csv(body)
train.head()


id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0  110936                             0.429        12058  355060   
1   41492                             0.010        21546  315150   
2   31300                             0.917        17531   84140   
3   19415                             0.049        15341  250510   
4   99379                             0.052        31400  198680   

   Count_3-6_months_late  Count_6-12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid sourcing_channel residence_area_type  target  
0                   13                C               Urban       1  
1                   21                A               Urban       1  
2                    7                C               Rural       0  
3                    9                A               Urban       1  
4                   12                B               Urban       1

In [58]:
train.columns

Index(['id', 'perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3-6_months_late', 'Count_6-12_months_late',
       'Count_more_than_12_months_late', 'application_underwriting_score',
       'no_of_premiums_paid', 'sourcing_channel', 'residence_area_type',
       'target'],
      dtype='object')

In [59]:
test.columns

Index(['id', 'perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3-6_months_late', 'Count_6-12_months_late',
       'Count_more_than_12_months_late', 'application_underwriting_score',
       'no_of_premiums_paid', 'sourcing_channel', 'residence_area_type'],
      dtype='object')

In [60]:
train.rename(index = str, columns = {'Count_3-6_months_late':'Count_3_6_months_late','Count_6-12_months_late':'Count_6_12_months_late'},inplace = True)

In [61]:
test.rename(index = str, columns = {'Count_3-6_months_late':'Count_3_6_months_late','Count_6-12_months_late':'Count_6_12_months_late'},inplace = True)

In [62]:
train.isnull().any(axis = 0)

id                                  False
perc_premium_paid_by_cash_credit    False
age_in_days                         False
Income                              False
Count_3_6_months_late                True
Count_6_12_months_late               True
Count_more_than_12_months_late       True
application_underwriting_score       True
no_of_premiums_paid                 False
sourcing_channel                    False
residence_area_type                 False
target                              False
dtype: bool

In [63]:
test.isnull().any(axis = 0)

id                                  False
perc_premium_paid_by_cash_credit    False
age_in_days                         False
Income                              False
Count_3_6_months_late                True
Count_6_12_months_late               True
Count_more_than_12_months_late       True
application_underwriting_score       True
no_of_premiums_paid                 False
sourcing_channel                    False
residence_area_type                 False
dtype: bool

In [64]:
train['Count_3_6_months_late'].fillna(train.Count_3_6_months_late.median(), inplace = True)
train['Count_6_12_months_late'].fillna(train.Count_6_12_months_late.median(), inplace = True)
train['Count_more_than_12_months_late'].fillna(train.Count_more_than_12_months_late.median(), inplace = True)
train['application_underwriting_score'].fillna(train.application_underwriting_score.median(), inplace = True)

In [65]:
test['Count_3_6_months_late'].fillna(train.Count_3_6_months_late.median(), inplace = True)
test['Count_6_12_months_late'].fillna(train.Count_6_12_months_late.median(), inplace = True)
test['Count_more_than_12_months_late'].fillna(train.Count_more_than_12_months_late.median(), inplace = True)
test['application_underwriting_score'].fillna(train.application_underwriting_score.median(), inplace = True)

In [66]:
test.isnull().any(axis=0)

id                                  False
perc_premium_paid_by_cash_credit    False
age_in_days                         False
Income                              False
Count_3_6_months_late               False
Count_6_12_months_late              False
Count_more_than_12_months_late      False
application_underwriting_score      False
no_of_premiums_paid                 False
sourcing_channel                    False
residence_area_type                 False
dtype: bool

In [67]:
train.isnull().any(axis = 0)

id                                  False
perc_premium_paid_by_cash_credit    False
age_in_days                         False
Income                              False
Count_3_6_months_late               False
Count_6_12_months_late              False
Count_more_than_12_months_late      False
application_underwriting_score      False
no_of_premiums_paid                 False
sourcing_channel                    False
residence_area_type                 False
target                              False
dtype: bool

In [68]:
train=pd.get_dummies(train)
train.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0  110936                             0.429        12058  355060   
1   41492                             0.010        21546  315150   
2   31300                             0.917        17531   84140   
3   19415                             0.049        15341  250510   
4   99379                             0.052        31400  198680   

   Count_3_6_months_late  Count_6_12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    2.0                     3.0   
3                    0.0                     0.0   
4                    0.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.02   
1                             0.0                           99.89   
2                             1.0                           98.69   
3                             0.0                           99.57   
4                             0.0                           99.87   

   no_of_premiums_paid  target  sourcing_channel_A  sourcing_channel_B  \
0                   13       1                   0                   0   
1                   21       1                   1                   0   
2                    7       0                   0                   0   
3                    9       1                   1                   0   
4                   12       1                   0                   1   

   sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
0                   1                   0                   0   
1                   0                   0                   0   
2                   1                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   residence_area_type_Rural  residence_area_type_Urban  
0                          0                          1  
1                          0                          1  
2                          1                          0  
3                          0                          1  
4                          0                          1

In [69]:
test=pd.get_dummies(test)
test.head()

id  perc_premium_paid_by_cash_credit  age_in_days  Income  \
0    649                             0.001        27384   51150   
1  81136                             0.124        23735  285140   
2  70762                             1.000        17170  186030   
3  53935                             0.198        16068  123540   
4  15476                             0.041        10591  200020   

   Count_3_6_months_late  Count_6_12_months_late  \
0                    0.0                     0.0   
1                    0.0                     0.0   
2                    0.0                     0.0   
3                    0.0                     0.0   
4                    1.0                     0.0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                             0.0                           99.89   
1                             0.0                           98.93   
2                             0.0                           99.21   
3                             0.0                           99.00   
4                             0.0                           99.17   

   no_of_premiums_paid  sourcing_channel_A  sourcing_channel_B  \
0                    7                   1                   0   
1                   19                   1                   0   
2                    2                   0                   1   
3                   11                   0                   1   
4                   14                   1                   0   

   sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   residence_area_type_Rural  residence_area_type_Urban  
0                          1                          0  
1                          0                          1  
2                          0                          1  
3                          1                          0  
4                          1                          0

In [70]:
x = train.drop(('target'),axis=1)
x = x.drop(('id'),axis=1).values

y = train['target'].values

In [71]:
x

array([[4.2900e-01, 1.2058e+04, 3.5506e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [1.0000e-02, 2.1546e+04, 3.1515e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [9.1700e-01, 1.7531e+04, 8.4140e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       ...,
       [0.0000e+00, 2.3372e+04, 3.0502e+05, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [3.9800e-01, 2.2641e+04, 3.9330e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [5.5000e-01, 1.5709e+04, 2.8014e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00]])

In [72]:
y

array([1, 1, 0, ..., 1, 1, 0])

In [73]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.40,random_state = 0)

In [74]:
print('x_train',x_train.shape)
print('x_test',x_test.shape)
print('y_train',y_train.shape)
print('y_test',y_test.shape)

x_train (47911, 15)
x_test (31942, 15)
y_train (47911,)
y_test (31942,)


In [75]:
x_train

array([[6.3100e-01, 1.9353e+04, 1.1061e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [2.2200e-01, 1.1325e+04, 9.3030e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [8.1000e-02, 1.9724e+04, 3.4160e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       ...,
       [5.1900e-01, 1.6437e+04, 1.9709e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [6.3400e-01, 1.3520e+04, 1.8263e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [6.3000e-02, 1.9719e+04, 2.1351e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00]])

In [76]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [77]:
from sklearn.linear_model import LogisticRegression 

In [78]:
log=LogisticRegression()

In [79]:
log.fit(x_train,y_train)

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [80]:
log.fit(x_test,y_test)

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [81]:
pred=log.predict(x_test)
pred

array([1, 1, 1, ..., 1, 1, 1])

In [82]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,pred)
score

0.9400475862500782

In [83]:
pred_prob=log.predict_proba(x_test)
pred_prob

array([[0.11705164, 0.88294836],
       [0.05549618, 0.94450382],
       [0.01977342, 0.98022658],
       ...,
       [0.01708392, 0.98291608],
       [0.07229576, 0.92770424],
       [0.02250144, 0.97749856]])

In [84]:
from sklearn.metrics import roc_auc_score
auc_score1 = roc_auc_score(y_test, pred_prob[:,1])

In [85]:
auc_score1

0.8289549238907202

In [86]:
validation = test.drop(('id'),axis = 1).values
validation

array([[1.0000e-03, 2.7384e+04, 5.1150e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [1.2400e-01, 2.3735e+04, 2.8514e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [1.0000e+00, 1.7170e+04, 1.8603e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       ...,
       [3.2500e-01, 1.8264e+04, 1.9657e+05, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [9.8300e-01, 1.6798e+04, 2.1215e+05, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [5.0000e-03, 2.4467e+04, 8.9190e+04, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00]])

In [87]:
validation = scaler.transform(validation)

In [88]:
prediction_proba =log.predict_proba(validation)

In [89]:
prediction_proba

array([[0.0091477 , 0.9908523 ],
       [0.02115709, 0.97884291],
       [0.08267268, 0.91732732],
       ...,
       [0.0384713 , 0.9615287 ],
       [0.24310488, 0.75689512],
       [0.02470456, 0.97529544]])

In [90]:
final_prediction = pd.DataFrame()


In [91]:
final_prediction['id'] = test.id
final_prediction['target'] = prediction_proba[:,1]

In [92]:
final_prediction

id    target
0         649  0.990852
1       81136  0.978843
2       70762  0.917327
3       53935  0.969684
4       15476  0.953057
5       64797  0.977052
6       67412  0.588865
7       44241  0.876420
8        5069  0.986571
9       16615  0.987709
10      84281  0.979782
11      82623  0.969285
12      86475  0.655477
13      68263  0.888749
14     113135  0.945750
15      45532  0.960138
16     102161  0.989485
17      84789  0.378477
18      62398  0.961724
19      70148  0.973569
20     102487  0.880929
21     100513  0.922566
22      92702  0.908732
23      25051  0.814010
24      92920  0.986438
25      25520  0.947895
26      81869  0.960451
27      75402  0.982210
28      34053  0.787527
29      21191  0.975769
...       ...       ...
34194   79950  0.983769
34195   30272  0.986434
34196   85914  0.990816
34197   10922  0.981689
34198   93046  0.983329
34199   52826  0.938097
34200   35994  0.981833
34201    1512  0.981848
34202   52077  0.966020
34203   95749  0.971408
34204   49946  0.973091
34205   66811  0.973462
34206   53438  0.988407
34207   24435  0.979764
34208   17848  0.959772
34209   53626  0.975206
34210   87268  0.985145
34211   58450  0.976263
34212   48188  0.981986
34213   44239  0.955837
34214   24582  0.943098
34215   79939  0.962631
34216   63759  0.974363
34217   63725  0.782320
34218   37116  0.962119
34219   81988  0.969873
34220   30326  0.981040
34221   65749  0.961529
34222   65686  0.756895
34223   93826  0.975295

[34224 rows x 2 columns]

In [95]:
final_prediction.to_csv("sample1.csv", index = False)